name: Rollout Scheduler

on:
  workflow_dispatch:
    inputs:
      schedule_time:
        description: 'Enter scheduled time for rollout (in format YYYY-MM-DD HH:MM)'
        required: true

jobs:
  write_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Write Schedule to CSV
        id: write_schedule
        run: |
          echo "scheduled_time" >> schedule.csv
          echo "${{ github.event.inputs.schedule_time }}" >> schedule.csv
          cat schedule.csv

  check_schedule:
    runs-on: ubuntu-latest
    needs: write_schedule
    steps:
      - name: Read and Check Schedule
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M')
          scheduled_time=$(tail -n 1 schedule.csv)

          echo "Current Time: $current_time"
          echo "Scheduled Time: $scheduled_time"

          if [ "$current_time" == "$scheduled_time" ]; then
            echo "Executing rollout operation..."
            # Add your rollout command here
          else
            echo "No rollout scheduled for now."
          fi
